name: Main Workflow

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    main:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - run: mkdir /tmp/artifacts

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: Build App
              run: npm run build

            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: build
                  token: ${{secrets.gh_token}}

            - name: Lighthouse Check
              uses: foo-software/lighthouse-check-action@master
              id: lighthouseCheck
              with:
                  outputDirectory: /tmp/artifacts
                  urls: 'https://www.vinisaveg.tech'
                  device: 'all'

            - name: Upload Lighthouse Artifacts
              uses: actions/upload-artifact@master
              with:
                  name: Lighthouse reports
                  path: /tmp/artifacts

            - name: Verify Lighthouse Check results
              uses: foo-software/lighthouse-check-status-action@master
              with:
                  lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
                  minAccessibilityScore: '80'
                  minBestPracticesScore: '80'
                  minPerformanceScore: '80'
                  minSeoScore: '80'
                  minProgressiveWebAppScore: '50'
